---
engine: markdown
---

# arl_sop_bp_ic {#sec-doc}


::: {.callout-note appearance="simple" title="docblock" collapse=false}


```julia
arl_sop_bp_ic(spatial_dgp, lam, cl, w, reps=1_000; chart_choice=TauTilde(),
  refinement=OrdinaryType(), rl_max=typemax(Int))
```
Compute the in-control average run length (ARL) of the EWMA chart based on the Box-Pierce type statistic for spatial ordinal patterns (SOPs) via simulation. The computation is multithreaded.
 
  * `spatial_dgp::ICSTS`: in-control spatial DGP.
  * `lam::Float64`: A scalar value for lambda for the EWMA chart.
  * `cl::Float64`: A scalar value for the control limit.
  * `w::Int`: An integer value for the window size for the BP-statistic.
  * `reps::Int`: An integer value for the number of repetitions. The default value is 1,000.
  * `chart_choice`: one of [`TauHat`](TauHat.qmd)`()`, [`KappaHat`](KappaHat.qmd)`()`, [`TauTilde`](TauTilde.qmd)`()`, [`KappaTilde`](KappaTilde.qmd)`()`.
  * `refinement`: [`OrdinaryType`](OrdinaryType.qmd)`()` for the classical SOP classification, or one of [`RotationType`](RotationType.qmd)`()`, [`DirectionType`](DirectionType.qmd)`()`, [`DiagonalType`](DiagonalType.qmd)`()`.
  * `rl_max::Int=typemax(Int)`: maximal run length after which a replication is stopped.
Returns the tuple `(ARL, standard error)`.
 


:::


