---
engine: julia
---

# arl_sacf {#sec-doc}
    

::: {.callout-note appearance="simple" title="docblock" collapse=false}    

arl*sacf(lam, cl, spatial*dgp::ICSP, d1::Int, d2::Int, reps=10_000)
 
Compute the in-control average run length (ARL), using the spatial autocorrelation  function (SACF) for a delay (d1, d2) combination. The function returns the ARL  for a given control limit `cl` and a given number of repetitions `reps`. 
 
The input arguments are:
 
  * `lam`: The smoothing parameter for the exponentially weighted moving average (EWMA) control chart.
  * `cl`: The control limit for the EWMA control chart.
  * `spatial_dgp`: The in-control spatial data generating process (DGP) to use for the SACF function.
  * `d1::Int`: The first (row) delay for the spatial process.
  * `d2::Int`: The second (column) delay for the spatial process.
  * `reps`: The number of repetitions to compute the ARL.


:::
    

 --- 
 
::: {.callout-note appearance="simple" title="docblock" collapse=false}    


```{julia}
#| eval: false
arl_sacf(lam, cl, sp_dgp::SpatialDGP, d1::Int, d2::Int, reps=10_000)

```

Compute the in-control average run length (ARL) using the spatial autocorrelation  function (SACF) for a delay (d1, d2) combination and an out-of-control process. 
 
The input arguments are: 
 
  * `lam`: The smoothing parameter for the exponentially weighted moving average (EWMA) control chart.
  * `cl`: The control limit for the EWMA control chart.
  * `sp_dgp`: The spatial data generating process (DGP) to use for the SACF function.
This can be one of the following: [`SAR1`](SAR1.qmd), [`SAR11`](SAR11.qmd), [`SAR22`](SAR22.qmd), [`SINAR11`](SINAR11.qmd), [`SQMA11`](SQMA11.qmd),  [`SQINMA11`](SQINMA11.qmd), or [`BSQMA11`](BSQMA11.qmd).
 
  * `d1::Int`: The first (row) delay for the spatial process.
  * `d2::Int`: The second (column) delay for the spatial process.
  * `reps`: The number of repetitions to compute the ARL.


:::
    

