---
engine: julia
---

# rl_sacf {#sec-doc}
    

::: {.callout-note appearance="simple" title="docblock" collapse=false}    


```{julia}
#| eval: false
rl_sacf(

```

lam, cl, d1::Int, d2::Int, p*reps::UnitRange, spatial*dgp::ICSP, dist_error::UnivariateDistribution )
 
Compute the in-control run length using the spatial autocorrelation function (SACF)  for a delay (d1, d2) combination. The function returns the run length for a given control limit `cl`.
 
The input arguments are:
 
  * `lam`: The smoothing parameter for the exponentially weighted moving average (EWMA) control chart.
  * `cl`: The control limit for the EWMA control chart.
  * `d1::Int`: The first (row) delay for the spatial process.
  * `d2::Int`: The second (column) delay for the spatial process.
  * `p_reps::UnitRange`: The number of repetitions to compute the run length. This
has to be a unit range of integers to allow for parallel processing, since the    function is called by `arl_sacf()`.
 
  * `spatial_dgp::ICSP`: The in-control spatial data generating process (DGP) to
use for the SACF function.
 
  * `dist_error::UnivariateDistribution`: The distribution to use for the error term in the
spatial process. This can be any univariate distribution from the `Distributions.jl` package.
 


:::
    

 --- 
 
::: {.callout-note appearance="simple" title="docblock" collapse=false}    


```{julia}
#| eval: false
rl_sacf(

```

lam, cl, d1::Int, d2::Int, p*reps::UnitRange, spatial*dgp::SpatialDGP,   dist*error::UnivariateDistribution, dist*ao::Union{UnivariateDistribution,Nothing} )
 
Compute the out-of-control run length using the spatial autocorrelation function (SACF).  The function returns the run length for a given control limit `cl` and a given number of  repetitions `reps`. 
 
The input arguments are:
 
  * `lam`: The smoothing parameter for the exponentially weighted moving average (EWMA)
control chart.
 
  * `cl`: The control limit for the EWMA control chart.
  * `d1::Int`: The first (row) delay for the spatial process.
  * `d2::Int`: The second (column) delay for the spatial process.
  * `p_reps::UnitRange`: The number of repetitions to compute the run length. This
has to be a unit range of integers to allow for parallel processing, since the    function is called by `arl_sacf()`.
 
  * `spatial_dgp::SpatialDGP`: The spatial data generating process (DGP) to use for
the SACF function. This can be one of the following: [`SAR1`](SAR1.qmd), [`SAR11`](SAR11.qmd), [`SAR22`](SAR22.qmd),    [`SINAR11`](SINAR11.qmd), [`SQMA11`](SQMA11.qmd), [`SQINMA11`](SQINMA11.qmd), or [`BSQMA11`](BSQMA11.qmd).
 


:::
    

